manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: ergonautkb
      url-base: https://github.com/ergonautkb
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3-branch
      import: app/west.yml
    - name: ergonautkb-zmk-module
      remote: ergonautkb
      revision: v0.3-branch
    - name: prospector-zmk-module
      remote: prospector
      revision: v2.1.0  # Use v2.0.0 for ZMK â‰¤0.3 (Zephyr 3.x)
      path: modules/prospector-zmk-module
  self:
    path: config
